### ISSUE TITLE
Needs a Readme

### ISSUE THREAD

**Issue by androidfanatic** [robfig/cron#112]

**Comment by JulienBreux** [comment]
https://godoc.org/github.com/robfig/cron

**Comment by alexellis** [comment]
If that's the readme then it should be better linked to in the root.. the readme could really be improved with:

* is this library being maintained or supported?
* what is the procedure for PRs?
* mentioning if there are open issues / bugs
* what it can be used for
* how to keep it running since after calling c.Start() the code exits from "Main"
* a complete example with a "main" function

And probably a few other key details.
