### ISSUE TITLE
Is the sort function of entries jobs is working correctly ?

### ISSUE THREAD

**Issue by canhlinh** [robfig/cron#136]
I have reviewed the code and found an issue in these line of code:

From line 54 at https://github.com/robfig/cron/blob/master/cron.go
```
type byTime []*Entry

func (s byTime) Len() int      { return len(s) }
func (s byTime) Swap(i, j int) { s[i], s[j] = s[j], s[i] }
func (s byTime) Less(i, j int) bool {
	// Two zero times should return false.
	// Otherwise, zero is "greater" than any other time.
	// (To sort it at the end of the list.)
	if s[i].Next.IsZero() {
		return false
	}
	if s[j].Next.IsZero() {
		return true
	}
	return s[i].Next.Before(s[j].Next)
}
```
You said `Two zero times should return false.` 
The first element is correct.
```
if s[i].Next.IsZero() {
		return false
}
```
The second element is wrong.
```
if s[j].Next.IsZero() {
		return true
}
```

**Comment by radu-munteanu** [comment]
It's OK.

From the Entry...
```
	// The next time the job will run. This is the zero time if Cron has not been
	// started or this entry's schedule is unsatisfiable
	Next time.Time
```
From Less...
```
	// (To sort it at the end of the list.)
```

So, Zero means it should be at the end. If the first element is zero, then it has a higher position than the second element, not lower. If the second element is zero, then it's like the max there is, so there is nothing than could be higher than that. It's not the perfect if statement on the first part, but the second if is good.

Sometimes dev comments can be confusing, just read the code and understand what the function wants to achieve.

What I'd do though, is change the if statements order, because it's useless to do a Swap if s[i].Next and s[j].Next are both zero.

```
	if s[j].Next.IsZero() {
		return true
	}
	if s[i].Next.IsZero() {
		return false
	}
```

**Comment by canhlinh** [comment]
Oh. i see. Thanks. I'll close this issue.
