### ISSUE TITLE
Support CRON_TZ

### ISSUE THREAD

**Issue by linmaosong2018** [robfig/cron#148]
Can we add support for CRON_TZ, to allow job specifications in different timezone? At the moment, do this requires crafting a converted job description string, plus detecting timezone changes (to re-create the job description string). Would be great if this package supports CRON_TZ. Quoting from Man page:

> The CRON_TZ specifies the time zone specific for the cron table. User type into the chosen table times in the time of the specified time zone. The time into log is taken from local time zone, where is the daemon running.

**Comment by robfig** [comment]
Hi, sorry for the long radio silence. This feature is currently supported on the v2 and v3 branches, except using the "TZ=" instead of "CRON_TZ=".  Looking into it more, I see that CRON_TZ is the official way to do so, so I've added support for that as well as moved to that as the recommendation for the v3 branch.

See the implementation here:
4813ba249658816f718777160762f8c48c747eab

Thanks!
