### ISSUE TITLE
Cron Next() is giving wrong time for timezone "America/Sao_Paulo"

### ISSUE THREAD

**Issue by Sreevani871** [robfig/cron#157]
Example code:
```
package main

import (
        "fmt"
        "time"

        "github.com/robfig/cron"
)

func main() {
        timezone := "America/Sao_Paulo"
        loc, err := time.LoadLocation(timezone)
        if err != nil {
                fmt.Println("err:", err)
        }

        sch, err := cron.ParseStandard("0 9 10 * *")
        if err != nil {
                fmt.Println(err)
        }
        l := time.Now().In(loc)

        fmt.Println(sch.Next(l))
}
```
The output supposed to be this
2018-11-10 09:00:00 -0200 -02
but getting next to next 
2018-12-10 09:00:00 -0200 -02

Can anyone help me? We are facing this issue in Production.

**Comment by robfig** [comment]
It turns out that the logic that finds the next time to activate a job does not properly handle daylight savings time transitions at midnight, as happens in Sao Paulo. I've fixed the issue with a test to prevent regression. Sorry for the problem and the long delay until a fix! You can see the fix in the linked commit, on the v3 branch. Please do let me know if you have any further issues.

**Comment by Sreevani871** [comment]
Thanks for the update
