### ISSUE TITLE
Cron runs multiple times on server with gobuild

### ISSUE THREAD

**Issue by theironnetworkorg** [robfig/cron#167]
I have a developed an application and created routes ( as REST api ) for different functionalities like complete a job, charge a job etc. There routes are then setup with cron to run every 10 minutes with following code.

```
package cron
import (
	"gopkg.in/robfig/cron.v2"
	"api/config"
)
func RunCron() {
	c := cron.New()
	c.AddFunc("@every 0h10m0s", RunAutoCharge)
	c.Start()
}

func RunAutoCharge(){
	utils.ExecuteCommand("sh " +config.GetBasePath() + "sh/auto_charge_bookings.sh")
}
```
the sh file mentioned in the function contains rest api url as follows which runs when cron runs 

```
#!/bin/bash
curl "127.0.0.1:8080/merchantname/auto-charge-bookings"
```

this setup works properly but charges the customers twice , on analysis I found that the api is running twice in five minutes which should not be 

Please help me to resolve the issue

**Comment by robfig** [comment]
That could happen if the application restarted, e.g. most people that run software using Docker have it configured to restart on failure or OOM. There is no way to guarantee charging someone exactly once like this.. you should use a database to store that information.

**Comment by CybotTM** [comment]
Hi! We have a similar use case in [Ofelia](https://github.com/netresearch/ofelia) (a Docker job scheduler built on go-cron) where we implement concurrency limiting using a semaphore pattern.

Our implementation uses a `jobSemaphore` that limits the maximum number of concurrent job executions across the scheduler. Here's the core approach:

```go
type jobSemaphore struct {
    maxConcurrent int
    current       int32
    mu            sync.Mutex
    cond          *sync.Cond
}

func (s *jobSemaphore) Acquire(ctx context.Context) bool {
    s.mu.Lock()
    defer s.mu.Unlock()
    
    for int(s.current) >= s.maxConcurrent {
        // Wait with context awareness
        if ctx.Err() != nil {
            return false
        }
        s.cond.Wait()
    }
    atomic.AddInt32(&s.current, 1)
    return true
}

func (s *jobSemaphore) Release() {
    atomic.AddInt32(&s.current, -1)
    s.cond.Broadcast()
}
```

This is then wrapped into job execution with context cancellation support.

Would be great to have this as a native `WithMaxConcurrency(n int) JobWrapper` option in go-cron, similar to how `DelayIfStillRunning` works but across all jobs rather than per-job.

Happy to contribute a PR if there's interest!
