### ISSUE TITLE
Enhancement: Subsecond schedules

### ISSUE THREAD

**Issue by mcandre** [robfig/cron#178]
As a unit tester, I want robfig/cron to accept schedule configurations with sub-second precision, such as running a job every 0.25 seconds, so that I can execute my test suites faster.

Currently, I am using a cron schedule of every 1 second, waiting 3 seconds, and counting how many times the job fired so far. But each test that waits 3 seconds, adds up to a longer and longer test suite.

**Comment by robfig** [comment]
Yeah, this would be helpful for the unit tests in this library too, which currently take 30 seconds for that exact reason.

**Comment by robfig** [comment]
Can you use a ConstantDelaySchedule, with cron.Every(25*time.Millisecond) ? 

It doesn't help if you're trying to test the cron spec parsing itself, but if you were trying to do that I'm not sure that it would be coherent to have an option to 1/10 the durations just for tests.

**Comment by robfig** [comment]
I'm going to close this, because I can't think of any reasonably straightforward way to implement this and I think it has limited value. If you want to test that you have the right cron spec, I recommend using the cron.Parser to get a cron.Schedule, then you can unit test your schedules by calling `schedule.Next(since)`.
