### ISSUE TITLE
Got this while doing a go build v3

### ISSUE THREAD

**Issue by mwei0210** [robfig/cron#209]
`cannot find module providing package gopkg.in/robfig/cron.v3`

any idea what might cause it?

**Comment by robfig** [comment]
Yep - since v3 uses modules, you should import it as github.com/robfig/cron/v3 instead. From what I understand, modules does not allow you to import the same module via different import paths, and since gokpg.in was a workaround for not having such a mechanism, I chose to use the github.com path instead. Please let me know if that doesn't work for you.

**Comment by mwei0210** [comment]
thanks @robfig it's building now but got referencing problem when writing code in ide, is that a workaround for that matter?

**Comment by mwei0210** [comment]
Thanks! I am able to build now but is there a workaround to referencing cron when writing code using `github.com/robfig/cron/v3`? Cause it doesn't seem to work anymore, or is that an ide issue?

**Comment by saraswat40** [comment]
Can you please fix the doc [here](https://godoc.org/gopkg.in/robfig/cron.v3) ( the import statement at the top ). I spent a long time figuring out this issue.
