### ISSUE TITLE
cannot find package "github.com/robfig/cron/v3"

### ISSUE THREAD

**Issue by naughtydevelopment** [robfig/cron#221]
I opened an issue for `jobrunner` before. But I think that issue it is belongs to here. https://github.com/bamzi/jobrunner/issues/14

`github.com/robfig/cron (download) package github.com/robfig/cron/v3: cannot find package "github.com/robfig/cron/v3" in any of: /usr/local/go/src/github.com/robfig/cron/v3 (from $GOROOT) /go/src/github.com/robfig/cron/v3 (from $GOPATH)`

**Comment by naughtydevelopment** [comment]
@bamzi/jobrunner changed the source as "gopkg.in/robfig/cron.v3" and it worked. I don't know this is still an issue for this repo or not. If it's not you can close the issue.

**Comment by robfig** [comment]
I suspect that you are using an older version of Go that lacks module support. I recommend upgrading, as you will find more and more libraries require modules to work over time.

**Comment by jtcotton63** [comment]
@robfig Thanks a ton for building a sweet piece of software!

I'm also getting the same error as @naughtydevelopment is. I'm using golang version 1.12.6 (1.12.7 is the current release).

Here's what I did:

* Following the instructions [on the readme](https://github.com/robfig/cron/tree/v3.0.0), I ran `go get github.com/robfig/cron/v3@v3.0.0`. However, this gave me an error message: `go: cannot use path@version syntax in GOPATH mode`. I did some digging on the internet but couldn't find a solution.
* Since I couldn't get the `go get` command from the readme to work, I tried getting `cron/v3` directly instead with the following command: `go get github.com/robfig/cron/v3`. This resulted in the same error that @naughtydevelopment had: `package github.com/robfig/cron/v3: cannot find package "github.com/robfig/cron/v3" in any of:
        /home/joseph_cotton/.gvm/gos/go1.12.6/src/github.com/robfig/cron/v3 (from $GOROOT)
        /home/joseph_cotton/.gvm/pkgsets/go1.12.6/global/src/github.com/robfig/cron/v3 (from $GOPATH)`
* Since that didn't work, I tried running `go get github.com/robfig/cron`. This downloaded the library just fine. I then changed the import statement in my code to be `import "github.com/robfig/cron/v3"` as described in the readme. However, when running `go build main.go`, I got the following error: `main.go:8:2: cannot find package "github.com/robfig/cron/v3" in any of:
        /home/joseph_cotton/.gvm/gos/go1.12.6/src/github.com/robfig/cron/v3 (from $GOROOT)
        /home/joseph_cotton/.gvm/pkgsets/go1.12.6/global/src/github.com/robfig/cron/v3 (from $GOPATH)`

Any ideas?

**Comment by jtcotton63** [comment]
I was able to resolve my own problems using the documentation. Turns out that the [docs](https://gopkg.in/robfig/cron.v3) specify `go get gopkg.in/robfig/cron.v3` as the get URL and `import "gopkg.in/robfig/cron.v3"` as the import path. Using those, it worked without any problems :)

**Comment by robfig** [comment]
I'm actually surprised -- I thought the behavior of Go Modules was to disallow importing a module except through its official import path, which is in this case would be "github.com/robfig/cron/v3". Tricky..

**Comment by Nikkhah** [comment]
I use **go get gopkg.in/robfig/cron.v3** as the get URL and **import "gopkg.in/robfig/cron.v3"** as the import path. but when I want to build my module, I face this error:
cannot load gopkg.in/robfig/cron.v3: cannot find module providing package gopkg.in/robfig/cron.v3
what can I do?
