### ISSUE TITLE
New fork with extended functionalities.

### ISSUE THREAD

**Issue by Vinggui** [robfig/cron#259]
Hi @robfig,
   I made this fork from your work called [Agenda](https://github.com/Vinggui/agenda) with extended options. It is still under evaluation, but I would appreciate some input from you, if possible.
   There is at least one function that I added and could possibly be a PR for your cron too:
```
func (c *Cron) Parse(spec string) (sch Schedule, err error) {
	return c.parser.Parse(spec)
}
```

Thanks in advance.

**Comment by robfig** [comment]
Cool, neat project. For me, I'm not sure it's useful enough to justify the additional API surface area. I think if the caller cares to call Parse, they should initialize the Parser and provide it to cron on construction rather than fetching the one it creates by default. Thanks for the offer though!
