### ISSUE TITLE
Undefine cron.Parse, 

### ISSUE THREAD

**Issue by fwhezfwhez** [robfig/cron#282]
```go
 undefined: cron.Parse
multiple-value cronObj.AddFunc() in single-value context
```

Which commit can I fix these two error?

I don't have permission to operate repo in the remote, which means I can't just fix code error and push it remotely.It will build error in the remote because the old version of cron.

Seriously speaking, why existed api has been changed or removed,  I hope you can rename a new method like AddFuncWay2(), AddFuncWay3(), rather than rewrite the published ones.

**Comment by robfig** [comment]
Your code is probably relying on v1 of cron. About 6 months ago I released v3 which returns an entry id in addition to an error from `AddFunc()` and made that the master branch, because I do not accept pull requests and issues on v1 any more. You can update your code to ignore the first return value, `_, err := cronObj.AddFunc()`

I take backwards compatibility very seriously -- I kept master branch backwards compatible for 6+ years before upgrading it to v3. I did not see how to evolve the library without making that update, and the corresponding update to your code is trivial. If you rely on your dependencies to not change, I recommend you use Go Modules.
