### ISSUE TITLE
code design question

### ISSUE THREAD

**Issue by alaingilbert** [robfig/cron#300]
In the current code, you are basically doing the same logic if the cron is running or not, but you go through some hoops: sending chan in a chan to get back the result...
You could just have a mutex that protect access to the `c.entries` variable instead and simplify the code quite a bit. (same goes for adding an entry)
https://github.com/robfig/cron/blob/208b4f76bfdd237a814619382b19c85097fa9142/cron.go#L204-L212

Is there any particular reason for this code design ?
Would you be interested if I make a PR to simplify the code a bit ?

( Awesome work by the way, I use this library for a couple years now :) )

**Comment by robfig** [comment]
I wrote this code many years ago, so I don't think I can accurately report anything that was going through my head at the time. But looking at it now, an extra goroutine is required by the functionality, and having that goroutine own the cron's state seemed easier and more clear than protecting it with a mutex. Also, it did not have so many controls in the past. Or, since it was early in Go's lifetime, perhaps it was a zealous application of the "share memory by communicating" proverb. 

Regardless, I think that rewriting it to use a mutex change would be a large one, and at this stage I think that library stability and reliability is the most important thing. 

Thank you for your interest and kind words.
