### ISSUE TITLE
CRON Expression Format does not work on macOS

### ISSUE THREAD

**Issue by YapingLi** [robfig/cron#310]
I wrote a simple code block to try out this cron library. I am using Mac. My macOS version is `10.15.2`, my Go version is `go version go1.13.7 darwin/amd64`.

Below is the complete code. It uses CRON Expression Format for spec, I don't think the cron job runs expectedly since the statement of "cron running:" is not printed out at all.
```
package main

import (
	"github.com/robfig/cron/v3"
	"log"
)

func main() {
	log.Println("START CRON JOB")
	i := 0
	c := cron.New()
	
	spec := "*/5 * * * * ?" //it sets the interval to be every 5s
        c.AddFunc(spec, func() {
		i++
		log.Println("cron running:", i)
	})
	c.Start()
        select{}
}
```
Below is the corresponding output. Fyi, here I had to CMD+C to force quit.
```
$ go run main.go
2020/05/11 14:04:30 START CRON JOB
^Csignal: interrupt
```

Then, I changed from above CRON expression format to Interval format, which is `spec := "@every 5s"` and keep everything else the same. Then the statement of "cron running:" starts being printed out. Here is output I saw:
```
$ go run main.go
2020/05/11 14:38:50 START CRON JOB
2020/05/11 14:38:55 cron running: 1
2020/05/11 14:39:00 cron running: 2
2020/05/11 14:39:05 cron running: 3
2020/05/11 14:39:10 cron running: 4
2020/05/11 14:39:15 cron running: 5
2020/05/11 14:39:20 cron running: 6
```

Above experiment tells me that the CRON expression format does not work on macOS. I don't think this is expected behavior, bu If it was, then this should be well documented and make it noticeble.

**Comment by robfig** [comment]
The expression format is documented here:
https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format

The first field is a number of minutes, so I would expect your example to print every 5 minutes. I assume you intended seconds, which you can do by following the example here:
https://godoc.org/github.com/robfig/cron#hdr-Alternative_Formats

I suppose that the confusion came because the first version of this library had a seconds field (which I regret), but the seconds field was not present by default in v2 or v3, to align with the cron spec on wikipedia. The current state appears well-documented to me.
