### ISSUE TITLE
Using mutex in Entries()

### ISSUE THREAD

**Issue by olicuzo** [robfig/cron#335]
Hi,

As I was reading the library code, I stumbled upon this
https://github.com/robfig/cron/blob/6a8421bcff44c2a9889075724070baaebf8dcd72/cron.go#L177-L180

Since the function is returning a snapshot of the entries, is the `c.runningMu.Lock()` really necessary? Maybe I'm missing something

**Comment by skowrons** [comment]
In the end it will always call the function `entrySnapshot()` which will use a range to iterate over all Entry structs in the Entries array. Range will copy the used slice described [here](https://golang.org/ref/spec#RangeClause).

So yes there are writes that can happen, like an execution of `Schedule()`, but it should be save to remove the mutex.

**Comment by skowrons** [comment]
Yes you will need this. Say you got a slice like `{A,B,C,D}`. When `entrypSnapshot()` runs it will use range to calculate the length of the slice and iterate over it. Say it will add `A` to the result slice but before it can add `B` the `Run()` and `Schedule()` functions for `A` finished. This will reorganize the slice to `{B,C,D,A}`. So because we are at the second iteration it will now add `C`.
Your end result would look like this if no other reorganization of the slice is happening `{A,C,D,A}`.

In the end it is really simple if there are writes from a concurrent job we will need a mutex.

**Comment by robfig** [comment]
Yes..  `c.running` may be modified from another goroutine, so that means that ALL access to it must be protected by a mutex.
