### ISSUE TITLE
[Question] Is there a way to get cron spec string from an Entry?

### ISSUE THREAD

**Issue by hibiken** [robfig/cron#343]
After adding a few jobs to `Cron`, is there a way to get a cron spec string associated with each entry?

```go
c := cron.New()
c.AddFunc("30 * * * *", func() { fmt.Println("Every hour on the half hour") })
c.AddFunc("30 3-6,20-23 * * *", func() { fmt.Println(".. in the range 3-6am, 8-11pm") })
c.AddFunc("CRON_TZ=Asia/Tokyo 30 04 * * *", func() { fmt.Println("Runs at 04:30 Tokyo time every day") })
c.AddFunc("@hourly",      func() { fmt.Println("Every hour, starting an hour from now") })
c.AddFunc("@every 1h30m", func() { fmt.Println("Every hour thirty, starting an hour thirty from now") })

// ... 

for _, entry := range c.Entries() {
   // Is there a way to get the spec string from each entry here?
}
```

**Comment by buildscientist** [comment]
@hibiken Not directly since the Entry struct doesn't store the SpecSchedule returned by parser.Parse(). 

You could pull Entry.Prev and Entry.Next (both are time.Time types) and determine the spec using some basic arithmetic.

Alternatively you'd need to submit a PR modifying the Entry struct to include the spec such that when cron.AddJob is called the string is included as an additional field.

**Comment by hibiken** [comment]
Got it. Thank you for the answer!
I can workaround this, but was curious if I can retrieve the string from each entry. 
If other people are also interested, I can open a PR to make this change :) 

Closing this issue for now.

**Comment by 0xNF** [comment]
Old issue, I'm aware, but I am interested in pulling the traditional cron string from a parsed Schedule.
