### ISSUE TITLE
passing information from one job to another

### ISSUE THREAD

**Issue by keith6014** [robfig/cron#362]
Lets say I have two seperate cron jobs A and B. B depends on A's output. Both run asyncnously. If there is no data for B it will return nil (or doesn't run at all). How can I pass the return value of A to B using cron library?

**Comment by skowrons** [comment]
I don't think there is a way with this library. Just use plain go concepts like channels.
```go
func main() {
	cha := make(chan int)
	c := cron.New()
	c.AddFunc("*/1 * * * *", func() {
		fmt.Println("Runs every minute and add int (5) to channel.")
		cha <- 5
	})
	c.AddFunc("*/2 * * * *", func() {
		fmt.Println("Runs every two minutes and load int from channel.")
		fmt.Println("From other function: ", <-cha)
	})
	c.Start()
	for {}
}
```
You would create a channel that holds your information that you want to pass to the other function. This is pretty much standard in go to allow communication between two goroutines which your function are. But be careful with buffered and unbuffered channels and reads from empty channels because this will make go goes panic.

**Comment by robfig** [comment]
Exactly ^

Cron does not have any way to create a DAG between tasks. I believe most folks use Airflow for that sort of thing. It is definitely a cool capability but unfortunately out of scope for this library. Thanks
