### ISSUE TITLE
Why can't I call addFunc in a loop

### ISSUE THREAD

**Issue by yangjinheng** [robfig/cron#376]
~~~go
package main

import (
	"fmt"

	"github.com/robfig/cron/v3"
)

func main() {
	c := cron.New()

	// OK
	// c.AddFunc("*/1 * * * *", func() {
	// 	fmt.Println(1)
	// })
	// c.AddFunc("*/2 * * * *", func() {
	// 	fmt.Println(2)
	// })

	// NOT OK
	for i := 1; i <= 2; i++ {
		cr := fmt.Sprintf("*/%d * * * *", i)
		c.AddFunc(cr, func() {
			fmt.Println(i)
		})
	}

	fmt.Printf("%#v\n", c.Entries())
	c.Start()
	select {}
}
~~~

**Comment by skowrons** [comment]
I don't really get the problem. If you would use the above code, there will be two cron jobs that execute within there defined interval.
Or is your problem that every job will print the value "3" instead of "1" and "2". This is a common mistake that people make when using goroutines. Just do something like this:
```go
for i := 1; i <= 2; i++ {
	cr := fmt.Sprintf("*/%d * * * *", i)
        i := 1
	c.AddFunc(cr, func() {
		fmt.Println(i)
	})
}
```
This Stackoverflow explains the problem really good. https://stackoverflow.com/questions/24586141/go-func-closure-in-loop
