### ISSUE TITLE
Cron time in seconds dosn't work

### ISSUE THREAD

**Issue by illud** [robfig/cron#382]
Im trying to call every 5 seconds, i dont want to use @every 5s, the program starts ok but dosn't do anything.
     
    package main
    
    import (
	    "fmt"
	    "github.com/robfig/cron/v3"
    )
    
    func main() {
	    c := cron.New()
	    c.AddFunc("5 * * * * *", printSeconds)
	    fmt.Println("CRON JOB STARTED")
	    c.Start()
	    select {}
    }
    
    func printSeconds(){
	    fmt.Println("Every 5 Seconds") 
    }

**Comment by skowrons** [comment]
First your expression says run on the fifth second of every minute not on every 5 seconds. For every five x you should use `*/5`.
Then you should start catching the error of `AddFunc`. When I use this code:

```go
func main() {
	c := cron.New()
	_, err := c.AddFunc("5 * * * * *", printSeconds)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("CRON JOB STARTED")
	c.Start()
	select {}
}

func printSeconds() {
	fmt.Println("Every 5 Seconds")
}
```

It will print the error `expected exactly 5 fields, found 6: [5 * * * * *]`. This is due to the removal of the sixth field with version 3. You could create your own parser that uses the second field.

This should be the code you want:

```go
func main() {

	c := cron.New(
		cron.WithParser(
			cron.NewParser(
				cron.SecondOptional | cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)))

	_, err := c.AddFunc("*/5 * * * * *", printSeconds)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("CRON JOB STARTED")
	c.Start()
	select {}
}

func printSeconds() {
	fmt.Println("Every 5 Seconds")
}
```

For more information about custom parser read after this part of the docu.
https://github.com/robfig/cron/blob/bc59245fe10efaed9d51b56900192527ed733435/doc.go#L57

**Comment by illud** [comment]
Thanks a lot this was what i need. ;P

**Comment by mengdodo** [comment]
```
	crontab := cron.New(cron.WithSeconds()) 
	_, _ = crontab.AddFunc(fmt.Sprintf("*/%s * * * * ?",viper.GetString("websocket.HeartBeatTimeOut")), cleanConnection)

	crontab.Start()
	defer crontab.Stop()
	select {}
```

**Comment by blizardinka** [comment]
Thanks a lot this was what i need. @skowrons

**Comment by joint-song** [comment]
@mengdodo Thank you, this really helps a lot for me. Then I can use 6-fields cron expression and @every{duration} at the same time.
