### ISSUE TITLE
Run every two days on odd "day"

### ISSUE THREAD

**Issue by Emixam23-FCMS** [robfig/cron#411]
Hey!

I don't know if it's a bug, but I need to have two crons, one on odd day, one on even.
I have this cron definition:

```
CronJob A: 0 12 1-31/2 * *
CronJob B: 0 12 2-30/2 * *
```

It seemed to work for the first execution, but two days after, it didn't run... Don't know if it's a known bug or a misuse of us :)

Thanks!

**Comment by robfig** [comment]
I think that should work. Is it possible that the process exited? If so, a goroutine dump (via SIGQUIT) should be able to identify if any goroutines are blocked in the cron library and where they are. If you see that again, please collect that information, because as-is I don't have enough to investigate with. Feel free to re-open, but closing as inactionable for now.
